### ISSUE TITLE
Use strings in TikiSdk.IDP.Key.sign message parameter or throw a specific error

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-js#111]
The TikiSdk.IDP.Key.sign method requires 2 parameters: a string key id and a byte array message. 

For a developer using the API is confusing to have to convert the message from a string to a byte array before signing.

The best option would be to accept a string as parameter and convert to bytearray in the method. 

Another approach would be to check if the incoming message is a byte array and throw an error if not.

**Comment by mike-audi** [comment]
Discussed during call. Works as intended. 

The trouble with strings is there are all different types of encodings, in particular we use lots of base64 strings. These need to be decoded to byte array differently than a UTF8 string (hence it's at the developers discretion). 

will not fix.
