### ISSUE TITLE
Create TIKI SDK Builder

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-js#5]
Create a Tiki SDK builder in dart code and expose as a JavaScript method.

Acceptance criteria
1 - TIKI SDK builds and returns an address
2 - TIKI SDK accepts an address as parameter to build the SDK

**Comment by jcockhren** [comment]
I'm closing this issue because, with the [release of 2.0](https://github.com/tiki/tiki-sdk-dart/pull/267), `TikiSdkBuilder` is no longer a thing. `TikiSdk.withAddress` and `TikiSdk.init` is the new way to go.
